export const DEFAULT_IMAGE_RULES:string = `{
	rules: [
		{
			type: "thumbnail",
			description: "Thumbnail should be small and match expected dimensions.",
			category: "meta",
			severity: "low",
			globs: ["thumbnail.png"],
			optimal: 144,
			max: 288,
			maxMipmaps: 0,
		},
		{
			type: "icons",
			description: "Icons should be compact.",
			category: "icons",
			severity: "medium",
			globs: ["graphics/icons/**.png"],
			optimal: 64,
			max: 64,
			maxMipmaps: 3,
		},
		{
			type: "item-group",
			description: "Item group icons.",
			category: "icons",
			severity: "medium",
			globs: ["graphics/item-group/**.png"],
			optimal: 128,
			max: 128,
			maxMipmaps: 3,
		},
		{
			type: "technology",
			description: "Technology icons.",
			category: "icons",
			severity: "medium",
			globs: ["graphics/technology/**.png"],
			optimal: 256,
			max: 512,
			maxMipmaps: 3,
		},
		{
			type: "achievement",
			description: "Achievement icons.",
			category: "icons",
			severity: "medium",
			globs: ["graphics/achievement/**.png"],
			optimal: 128,
			max: 256,
			maxMipmaps: 3,
		},
		{
			type: "imageOptimization",
			description: "Images should be optimized",
			category: "rest",
			severity: "low",
			globs: ["**.png"],
		},
	],
}`
